### ASSIGNMENT

1.Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.
Expected Output:
[[ 2 3 4]
[ 5 6 7]
[ 8 9 10]]


2. Write a NumPy program to create a null vector of size 10 and update the sixth value to 11.
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]


3. Write a NumPy program to create an array with values ranging from 12 to 38.
Expected Output:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]


4. Write a NumPy program to reverse an array (the first element becomes the last).
Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

5. Write a NumPy program to convert an array to a floating type.
Sample output:
Original array
[1, 2, 3, 4]
Array converted to a float type:
[ 1. 2. 3. 4.]


6. Write a NumPy program to create a 2D array with 1 on the border and 0 inside.
Expected Output:
Original array:
[[ 1. 1. 1. 1. 1.]
...................
[ 1. 1. 1. 1. 1.]]

7. Write a NumPy program to find the number of elements in an array. It also finds the length of one array element in bytes and the total bytes consumed by the elements.
Expected Output:
Size of the array: 3
Length of one array element in bytes: 8
Total bytes consumed by the elements of the array: 24

In [1]:
import numpy as np

1. Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10. Expected Output: [[ 2 3 4] [ 5 6 7] [ 8 9 10]]

In [29]:
a = np.arange(2,11)
a = np.matrix(a.reshape(3,3))
print(a)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


2. Write a NumPy program to create a null vector of size 10 and update the sixth value to 11.
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

In [28]:
a = np.zeros(10)
print(a)
a[5] = 11

print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


3. Write a NumPy program to create an array with values ranging from 12 to 38.
Expected Output:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]

In [31]:
a = np.arange(12,38)

print(a)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


4. Write a NumPy program to reverse an array (the first element becomes the last).
Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

In [34]:
print(a[::-1])


[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


5. Write a NumPy program to convert an array to a floating type.
Sample output:
Original array
[1, 2, 3, 4]
Array converted to a float type:
[ 1. 2. 3. 4.]

In [39]:
a = np.array([1,2,3,4])
print(a)
print(a.astype(float))

[1 2 3 4]
[1. 2. 3. 4.]


6. Write a NumPy program to create a 2D array with 1 on the border and 0 inside.
Expected Output:
Original array:
[[ 1. 1. 1. 1. 1.]
...................
[ 1. 1. 1. 1. 1.]]

In [44]:
# Define the size of the 2D array
rows, cols = 5, 5

# Create a 2D array of zeros
array_2d = np.zeros((rows, cols))

# Set the border elements to 1
array_2d[0, :] = 1  # First row
array_2d[-1, :] = 1  # Last row
array_2d[:, 0] = 1  # First column
array_2d[:, -1] = 1  # Last column

# Print the original array
print("Original array:")
print(array_2d)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


7. Write a NumPy program to find the number of elements in an array. It also finds the length of one array element in bytes and the total bytes consumed by the elements.
Expected Output:
Size of the array: 3
Length of one array element in bytes: 8
Total bytes consumed by the elements of the array: 24

In [43]:
import numpy as np

# Create the NumPy array
arr = np.array([1, 2, 3], dtype=np.int64)

# Find the size of the array (number of elements)
size_of_array = arr.size

# Find the length of one array element in bytes
element_size_in_bytes = arr.itemsize

# Find the total bytes consumed by the elements of the array
total_bytes_consumed = size_of_array * element_size_in_bytes

# Print the results
print("Size of the array:", size_of_array)
print("Length of one array element in bytes:", element_size_in_bytes)
print("Total bytes consumed by the elements of the array:", total_bytes_consumed)


Size of the array: 3
Length of one array element in bytes: 8
Total bytes consumed by the elements of the array: 24
